/* widget-naming.test.svelte.js generated by Svelte v5.56.8 */
import * as $ from 'svelte/internal/client';
import { test } from 'node:test';
import assert from 'node:assert';
import { collector, report } from './check.js';
import { mount, flushSync } from 'svelte';
import Widget from './Widget.svelte.js';
import Select from './Select.svelte.js';
import Range from './Range.svelte.js';

const { ok, eq, results } = collector();

const OPTS_A = {
	plotType: {
		el: Select,
		label: 'Plot type',
		default: 'p',
		props: { options: ['p', 'l', 'h'] }
	},
	comp1: {
		el: Range,
		label: 'Component',
		default: 1,
		props: { min: 1, max: 10, step: 1, decNum: 0 }
	},
	custom: {
		el: Select,
		label: 'Has own name',
		default: 'a',
		props: { options: ['a', 'b'], ariaLabel: 'explicitly named' }
	},
	bare: { el: Select, default: 'x', props: { options: ['x', 'y'] } }
};

const OPTS_B = {
	plotType: {
		el: Select,
		label: 'Plot type',
		default: 'p',
		props: { options: ['p', 'l'] }
	}
};

function mountWidget(options, title) {
	const target = document.createElement('div');

	document.body.appendChild(target);

	const st = $.proxy({ v: {} });

	for (const k of Object.keys(options)) st.v[k] = options[k].default;

	mount(Widget, {
		target,
		props: {
			title,
			options,
			get value() {
				return st.v;
			},

			set value(x) {
				st.v = x;
			}
		}
	});

	flushSync();

	return { target, st };
}

/* the accessible name a screen reader would compute, resolved within the whole document */
function nameOf(root, el) {
	if (!el) return 'NO-CONTROL';

	/* aria-labelledby first: that is the order the accessible-name algorithm uses, so a
	   regression which emitted both attributes would be caught rather than hidden */
	const ref = el.getAttribute('aria-labelledby');

	if (ref) {
		const t = document.getElementById(ref);

		return t ? t.textContent : 'DANGLING';
	}

	return el.getAttribute('aria-label') || null;
}

const controls = (t) => [
	...t.querySelectorAll('[role="radiogroup"],[role="slider"],[role="spinbutton"],input')
];

const A = mountWidget(OPTS_A, 'Panel A');
const B = mountWidget(OPTS_B, 'Panel B');

const ca = controls(A.target),
	cb = controls(B.target);

eq('Panel A renders 4 controls', ca.length, 4);
eq('1. Panel A plot type is named', nameOf(A.target, ca[0]), 'Plot type');
eq('1. Panel A component is named', nameOf(A.target, ca[1]), 'Component');
eq('1. Panel B plot type is named', nameOf(B.target, cb[0]), 'Plot type');
eq('2. own ariaLabel still wins', nameOf(A.target, ca[2]), 'explicitly named');
eq('2. ...via aria-label', ca[2].getAttribute('aria-label'), 'explicitly named');
eq('2. ...and not also labelledby', ca[2].getAttribute('aria-labelledby'), null);
eq('3. label-less control stays unnamed', nameOf(A.target, ca[3]), null);

// 1. no duplicate ids anywhere in the document
const ids = [...document.querySelectorAll('[id]')].map((e) => e.id);

eq('1. no duplicate ids in the document', ids.length, new Set(ids).size);

const idA = ca[0].getAttribute('aria-labelledby'),
	idB = cb[0].getAttribute('aria-labelledby');

ok('1. both panels actually carry an id', !!idA && !!idB, `A=${idA} B=${idB}`);
ok('1. the two panels use different ids', !!idA && !!idB && idA !== idB, `A=${idA} B=${idB}`);

// 3. never point at nothing
for (const [i, el] of [...ca, ...cb].entries()) {
	const r = el.getAttribute('aria-labelledby');

	if (r) ok(`3. aria-labelledby #${i} resolves`, !!document.getElementById(r), `dangling ${r}`);
}

// 4. values untouched by rendering
eq('4. panel A value unchanged', JSON.stringify(A.st.v), JSON.stringify({ plotType: 'p', comp1: 1, custom: 'a', bare: 'x' }));

eq('4. panel B value unchanged', JSON.stringify(B.st.v), JSON.stringify({ plotType: 'p' }));
report(test, assert, results);