/* widget-dynamic.test.svelte.js generated by Svelte v5.56.8 */
import * as $ from 'svelte/internal/client';
import { test } from 'node:test';
import assert from 'node:assert';
import { collector, report } from './check.js';
import { mount, flushSync } from 'svelte';
import Widget from './Widget.svelte.js';
import Select from './Select.svelte.js';
import Range from './Range.svelte.js';

const { ok, eq, results } = collector();
const sel = (opts) => ({ el: Select, props: { options: opts } });

function mountWidget(initialOptions, initialValue, title = '') {
	const target = document.createElement('div');

	document.body.appendChild(target);

	const st = $.proxy({ opts: initialOptions, v: initialValue });

	mount(Widget, {
		target,
		props: {
			title,
			get options() {
				return st.opts;
			},

			get value() {
				return st.v;
			},

			set value(x) {
				st.v = x;
			}
		}
	});

	flushSync();

	return { target, st };
}

const controls = (t) => [
	...t.querySelectorAll('[role="radiogroup"],[role="slider"],[role="spinbutton"],input')
];

/* the name a reader would compute, resolved against the whole document */
function nameOf(el) {
	const ref = el.getAttribute('aria-labelledby');

	if (ref) {
		const t = document.getElementById(ref);

		return t ? t.textContent : 'DANGLING';
	}

	return el.getAttribute('aria-label') || null;
}

/* every control names itself with its OWN label, every reference resolves, ids are unique */
function checkConsistent(tag, target, expected) {
	const cs = controls(target);

	eq(`${tag}: control count`, cs.length, expected.length);
	cs.forEach((c, i) => eq(`${tag}: control ${i} named`, nameOf(c), expected[i]));

	const refs = cs.map((c) => c.getAttribute('aria-labelledby')).filter(Boolean);

	ok(`${tag}: every reference resolves`, refs.every((r) => !!document.getElementById(r)), refs.filter((r) => !document.getElementById(r)).join(','));

	const all = [...document.querySelectorAll('[id]')].map((e) => e.id);

	eq(`${tag}: no duplicate id in the document`, all.length, new Set(all).size);
}

// ---------------------------------------------------------------- reorder / insert
{
	const A = {
		alpha: { ...sel(['a', 'b']), label: 'Alpha', default: 'a' },
		beta: { ...sel(['c', 'd']), label: 'Beta', default: 'c' }
	};

	const W = mountWidget(A, { alpha: 'a', beta: 'c' });

	checkConsistent('initial', W.target, ['Alpha', 'Beta']);

	// insert BEFORE the existing ones - the case that actually challenges a positional id
	W.st.opts = {
		zero: { ...sel(['x', 'y']), label: 'Zero', default: 'x' },
		alpha: { ...sel(['a', 'b']), label: 'Alpha', default: 'a' },
		beta: { ...sel(['c', 'd']), label: 'Beta', default: 'c' }
	};

	flushSync();
	checkConsistent('after insert at front', W.target, ['Zero', 'Alpha', 'Beta']);

	// reverse the order
	W.st.opts = {
		beta: { ...sel(['c', 'd']), label: 'Beta', default: 'c' },
		alpha: { ...sel(['a', 'b']), label: 'Alpha', default: 'a' },
		zero: { ...sel(['x', 'y']), label: 'Zero', default: 'x' }
	};

	flushSync();
	checkConsistent('after reorder', W.target, ['Beta', 'Alpha', 'Zero']);

	// remove one
	W.st.opts = { beta: { ...sel(['c', 'd']), label: 'Beta', default: 'c' } };

	flushSync();
	checkConsistent('after removal', W.target, ['Beta']);
	eq('values survived every reshuffle', JSON.stringify(W.st.v), JSON.stringify({ alpha: 'a', beta: 'c', zero: 'x' }));
}

// ------------------------------------------------- callable label + hiddenWhen round trip
{
	const OPTS = {
		mode: { ...sel(['single', 'both']), label: 'Mode', default: 'single' },
		stat: {
			el: Range,
			props: { min: 1, max: 10, step: 1, decNum: 0 },
			default: 4,
			label: (v) => v.mode === 'single' ? 'FoM (single)' : 'FoM',
			hiddenWhen: (v) => v.mode === 'both'
		}
	};

	const W = mountWidget(OPTS, { mode: 'single', stat: 4 });

	checkConsistent('label fn, shown', W.target, ['Mode', 'FoM (single)']);
	W.st.v.mode = 'both'; // hides 'stat'
	flushSync();
	checkConsistent('hiddenWhen hides it', W.target, ['Mode']);
	eq('hidden control keeps its value', W.st.v.stat, 4);
	W.st.v.mode = 'single'; // brings it back, label text as before
	flushSync();
	checkConsistent('shown again', W.target, ['Mode', 'FoM (single)']);
	eq('value still intact after the round trip', W.st.v.stat, 4);
}

// ------------------------------------------------- the widget's own group name
{
	const OPTS = { a: { ...sel(['1', '2']), label: 'A', default: '1' } };
	const untitled = mountWidget(OPTS, { a: '1' });
	const uw = untitled.target.querySelector('.widget');

	eq('no title: no group role', uw.getAttribute('role'), null);
	eq('no title: no aria-labelledby', uw.getAttribute('aria-labelledby'), null);

	const P = mountWidget(OPTS, { a: '1' }, 'Panel A');
	const Q = mountWidget(OPTS, { a: '1' }, 'Panel B');

	const pw = P.target.querySelector('.widget'),
		qw = Q.target.querySelector('.widget');

	eq('titled: wrapper is a group', pw.getAttribute('role'), 'group');

	const pr = pw.getAttribute('aria-labelledby'),
		qr = qw.getAttribute('aria-labelledby');

	ok('titled: reference resolves', !!document.getElementById(pr), `dangling ${pr}`);
	eq('titled: group is named after its title', document.getElementById(pr)?.textContent, 'Panel A');
	eq('titled: second group named after its own title', document.getElementById(qr)?.textContent, 'Panel B');
	ok('titled: two panels use different title ids', !!pr && !!qr && pr !== qr, `${pr} vs ${qr}`);

	/* A titled widget with no options never renders its heading: the effect which fills
	   'value' returns early, so '{#if value}' stays false for good. The group must not name
	   itself after a heading which will never exist. */
	const empty = mountWidget(undefined, undefined, 'Panel C');

	const ew = empty.target.querySelector('.widget');
	const er = ew.getAttribute('aria-labelledby');

	eq('no options: heading is not rendered', empty.target.querySelector('h2'), null);
	ok('no options: no dangling group reference', !er || !!document.getElementById(er), `dangling ${er}`);
	eq('no options: no group role either', ew.getAttribute('role'), null);
}

report(test, assert, results);